batch_size: 22
num_batches: 1
runs: 50
system: Ni-Pd-H

guidance:
  mean_coordination:
    mode: huber
    alpha: 3.0
    "[Pd,Ni]-H": 6

forward_weight: 0.01
backward_weight: 0.01
normalize: true
self_rec_steps: 3
back_step: 2
algorithm: 1
diffusion_guidance_factor: 2.0
gpu: 2

oom_retries: 30
oom_backoff_percent: 80
min_batch_size: 1
oom_wait_seconds: 10

base_dir: ./
log_file: log.txt
dry_run: false
