batch_size: 20
runs: 50
system: Li-Co-O

guidance:
  type: volume
  parameters: 80.0

forward_weight: 0.01
backward_weight: 0.01
normalize: true
self_rec_steps: 3
back_step: 2
algorithm: 1
gpu: 0

base_dir: ./
log_file: log.txt
dry_run: false
